services:
  distributor:
    build:
      context: .
      dockerfile: Dockerfile.distributor
    ports:
      - '${DISTRIBUTOR_PORT}:${DISTRIBUTOR_PORT}'
    env_file:
      - .dockerenv
    networks:
      - catndog-network

  lobby:
    build:
      context: .
      dockerfile: Dockerfile.lobby
    ports:
      - '${LOBBY_PORT}:${LOBBY_PORT}'
    env_file:
      - .dockerenv
    networks:
      - catndog-network

  matching:
    build:
      context: .
      dockerfile: Dockerfile.matching
    ports:
      - '${MATCHING_PORT}:${MATCHING_PORT}'
    env_file:
      - .dockerenv
    networks:
      - catndog-network

networks:
  catndog-network:
    driver: bridge

